drop table if exists bookmarks;

create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title text,
    url text,
    description text,
    rating INTEGER
);

insert into bookmarks
    (title, url, description, rating)
    values
        ('Bloc', 'http://www.bloc.com', 'test 1', 1),
        ('google', 'http://www.google.com', 'test 2', 2),
        ('yahoo', 'http://www.yahoo.com', 'test 3', 3),
        ('aol', 'http://www.aol.com', 'test 4', 4),
        ('facebook', 'http://www.facebook.com', 'test 5', 5),
        ('espn', 'http://www.espn.com', 'test 6', 1),
        ('cnn', 'http://www.cnn.com', 'test 7', 2),
        ('bbc', 'http://www.bbc.com', 'test 8', 3),
        ('amazon', 'http://www.amazon.com', 'test 9', 4),
        ('netflix', 'http://www.netflix.com', 'test 10', 5);